permalink: pretty

theme: jekyll-theme-minimal
title: Ian Ansell
description: things about me and stuff

#logo: [Location of the logo]

defaults:
    -
      scope:
        path: "" 
      values:
        sidebar: jazz jazz jazz